CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(25) UNIQUE NOT NULL,
    password VARCHAR(250) NOT NULL,
    email VARCHAR(320) UNIQUE NOT NULL,
    full_name VARCHAR(75),
    creation_date TIMESTAMP NOT NULL
);